global:
  scrape_interval: 15s # El agente buscará métricas cada 15 segundos
  evaluation_interval: 15s

scrape_configs:
  # 1. Monitoreo de la propia infraestructura de Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. Monitoreo de tu API de Flask (To-Do API)
  - job_name: 'todo-api'
    scrape_timeout: 10s
    metrics_path: '/metrics' # El endpoint de observabilidad que creamos en app.py
    static_configs:
      # Explicación de los targets:
      # - 'web:5000' funciona cuando levantas todo con docker-compose (usa el DNS interno de Docker)
      # - 'host.docker.internal:5000' permite a Prometheus (en contenedor) ver tu app si la corres con 'python src/app.py' fuera de Docker
      - targets: ['web:5000']
      